docker run --rm   --name pg-docker -e POSTGRES_PASSWORD=postgres -d -p 5432:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data  postgres

CREATE DATABASE b3data

CREATE TABLE IF NOT EXISTS B3_ACOES_HISTORICO (
    ID_ACOES_HIST SERIAL PRIMARY KEY,
    DAT_INFO DATE NOT NULL DEFAULT CURRENT_DATE,
    TICKER VARCHAR(20) NOT NULL,
    PRECO NUMERIC(20,4) NOT NULL,
    DIVIDEND_YIELD NUMERIC(20,4),
    PRECO_SOBRE_LUCRO NUMERIC(20,4),
    PRECO_SOBRE_VALOR_PATRIMONIAL NUMERIC(20,4),
    LUCRO_POR_ACAO NUMERIC(20,4),
    VALOR_POR_ACAO NUMERIC(20,4),
    ROIC NUMERIC(20,4),
    ROA NUMERIC(20,4),
    ROE NUMERIC(20,4),
    PSR NUMERIC(20,4),
    CAGR_LUCRO NUMERIC(20,4),
    CAGR_RECEITA NUMERIC(20,4),
    PASSIVOS_SOBRE_ATIVOS NUMERIC(20,4),
    PATRIMONIO_SOBRE_ATIVOS NUMERIC(20,4),
    PRECO_SOBRE_ATV_CIRCULANTE NUMERIC(20,4),
    PRECO_SOBRE_CAPITAL_GIRO NUMERIC(20,4),
    DIVIDA_LIQ_SOBRE_PATRIMONIO  NUMERIC(20,4),
    DIVIDA_LIQ_SOBRE_EBIT NUMERIC(20,4),
    ENTERPRISE_VALUE_SOBRE_EBIT  NUMERIC(20,4),
    PRECO_SOBRE_EBIT NUMERIC(20,4),
    PRECO_SOBRE_ATIVOS NUMERIC(20,4),
    MARGEM_BRUTA NUMERIC(20,4),
    MARGEM_EBIT NUMERIC(20,4),
    MARGEM_LIQUIDA NUMERIC(20,4),
    LIQUIDEZ_MEDIA_DIARIA NUMERIC(20,4),
    LIQUIDEZ_CORRENTE NUMERIC(20,4),
    GIRO_ATIVOS NUMERIC(20,4),
    PEG_RATIO NUMERIC(20,4),
    VALOR_DE_MERCADO NUMERIC(20,4)
);

CREATE  INDEX IDX_B3_ACOES_HISTORICO_BY_TICKER ON B3_ACOES_HISTORICO (TICKER);

CREATE  INDEX IDX_B3_ACOES_HISTORICO_BY_DAT ON B3_ACOES_HISTORICO (DAT_INFO);



CREATE TABLE IF NOT EXISTS PORTFOLIO (
    ID_PORTFOLIO SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    TICKERS VARCHAR(3000) NOT NULL
);

